parameters:
    voting.class: SymfonyContrib\Bundle\VotingBundle\Voting
    voting.doctrine.event_subscriber.class: SymfonyContrib\Bundle\VotingBundle\Doctrine\EventSubscriber

services:
    voting:
        class: %voting.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context
        calls:
            - [setAnonValue, [%voting.anon_value%]]
            - [setRequest, ['@?request=']]
